[workspace]
members = ["entry/seajob", "entry/auth", "entry/mind", "service", "entity", "migration", "common", "dto"]
resolver = "1"

[profile.release]
codegen-units = 1
strip = true
lto = true
opt-level = "z"
