[package]
name = "seajob-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.8.0"
listenfd = "1.0.1"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
tokio = "1.39.1"

[profile.release]
codegen-units = 1
strip = true
lto = true
opt-level = "z"