[package]
name = "seajob-dto"
version = "0.1.0"
edition = "2021"

[lib]
name = "seajob_dto"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0.204", features = ["derive"] }
validator = "0.18.1"
validator_derive = "0.18.1"
