name: deploy

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Builds
        uses: docker/setup-buildx-action@v2

      - name: Login to Alibaba Cloud Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.cn-shenzhen.aliyuncs.com
          username: ${{ secrets.ALIYUN_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}

      - name: Set commit SHA
        run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -f Dockerfile -t seajob-server .

      - name: Tag Docker image
        run: |
          docker tag seajob-server registry.cn-shenzhen.aliyuncs.com/aleksichen/seajob-server:latest
          docker tag seajob-server registry.cn-shenzhen.aliyuncs.com/aleksichen/seajob-server:$SHORT_SHA

      - name: Push Docker image
        run: |
          docker push registry.cn-shenzhen.aliyuncs.com/aleksichen/seajob-server:${{ env.SHORT_SHA }}
          docker push registry.cn-shenzhen.aliyuncs.com/aleksichen/seajob-server:latest
